apiVersion: v1
kind: Namespace
metadata:
  name: email-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ses-sender-sa
  namespace: email-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::792248914698:role/eks-ses-irsa-role
